/**
 * Sidebar 组织原则：引擎优先，产品殿后。
 *
 * 顶层为「显式学习路径」，内层目录仍用 autogenerated（往 guide / architecture
 * 里加文档会自动出现，无需改这里）。这样既有清晰的首页阅读顺序，又不牺牲可维护性。
 *
 * 顺序：
 *   1. 介绍（intro）
 *   2. 快速上手（入门）
 *   3. 指南（怎么做）
 *   4. 架构设计（怎么实现）
 *   5. API 参考
 *   6. 二次开发（进阶）
 *   7. 家族产品 —— 基于 ice-render 构建的上层应用（Entity Designer / ice-chart /
 *      ice-web-components），放在最底部，明确「它们是引擎之上的产品」。
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 顶层拆成两个明确的分组，把「引擎」与「基于引擎封装的上层应用」在导航上钉死：
  //   - ice-render 引擎：本站核心，讲渲染引擎本身怎么用、怎么实现
  //   - 家族产品 · 应用层：基于引擎封装的上层产品（Entity Designer / ice-chart / ice-web-components）
  // 内层目录仍用 autogenerated，新增文档自动收录，无需改这里。
  tutorialSidebar: [
    {
      type: 'category',
      label: 'ice-render 引擎',
      items: [
        'intro',
        { type: 'autogenerated', dirName: 'getting-started' },
        { type: 'autogenerated', dirName: 'guide' },
        { type: 'autogenerated', dirName: 'architecture' },
        { type: 'autogenerated', dirName: 'api' },
        { type: 'autogenerated', dirName: 'advanced' },
      ],
    },
    {
      type: 'category',
      label: '家族产品 · 应用层',
      items: [
        { type: 'autogenerated', dirName: 'entity-designer' },
        { type: 'autogenerated', dirName: 'ice-chart' },
        { type: 'autogenerated', dirName: 'ice-web-components' },
      ],
    },
  ],
};

module.exports = sidebars;
