/**
 * Sidebar 组织原则：引擎优先，产品殿后；显式三层编号 + 缩进。
 *
 * 顶层拆成两个分组：
 *   1. ice-render 引擎        —— 本站核心，讲渲染引擎本身怎么用、怎么实现
 *   2. 家族产品 · 应用层      —— 基于引擎封装的上层产品（Entity Designer / ice-chart / ice-web-components）
 *
 * 内层目录全部「显式列举」（不再用 autogenerated），编号规则对齐正文 CSS 计数器：
 *   - 一级分组：1. / 2.
 *   - 二级分组：1.1 / 1.2 / 1.3 ...
 *   - 三级文档：1.1.1 / 1.2.1 / 1.3.1 ...
 *
 * 取舍：显式列举会牺牲「新增文档自动出现」的便利性（加文档要手动在这里补一行），
 * 但换来了稳定、可读、与正文序号一致的信息架构。当前文档集已收敛稳定，优先可读性。
 *
 * 加新文档时：在对应 category 的 items 里补一个
 *   { type: 'doc', id: '<dir>/<file-without-number-prefix>', label: '<编号> <标题>' }
 * 即可；doc ID 中的数字前缀（如 architecture/01-runtime → architecture/runtime）由
 * Docusaurus numberPrefixes 自动剥离，写 id 时用剥离后的纯净路径。
 */

// @ts-check

// 各包版本号单一来源（见 site-versions.js）；左侧菜单的引擎分组与产品项都从这里取
const V = require('./site-versions');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: `1. ice-render 引擎 v${V.iceRender}`,
      items: [
        { type: 'doc', id: 'intro', label: '1.1 介绍' },
        {
          type: 'category',
          label: '1.2 快速上手',
          items: [
            { type: 'doc', id: 'getting-started/installation', label: '1.2.1 安装' },
            { type: 'doc', id: 'getting-started/your-first-scene', label: '1.2.2 你的第一个场景' },
          ],
        },
        {
          type: 'category',
          label: '1.3 指南',
          items: [
            { type: 'doc', id: 'guide/accessibility', label: '1.3.1 无障碍（a11y）' },
            { type: 'doc', id: 'guide/animation', label: '1.3.2 动画' },
            { type: 'doc', id: 'guide/code-display', label: '1.3.3 代码展示规范' },
            { type: 'doc', id: 'guide/coordinate-system', label: '1.3.4 坐标系与变换' },
            { type: 'doc', id: 'guide/core-concepts', label: '1.3.5 核心概念' },
            { type: 'doc', id: 'guide/dsl', label: '1.3.6 DSL 与 AI Agent 接入' },
            { type: 'doc', id: 'guide/events', label: '1.3.7 事件系统' },
            { type: 'doc', id: 'guide/group-and-layout', label: '1.3.8 分组与布局' },
            { type: 'doc', id: 'guide/line-and-link', label: '1.3.9 连线' },
            { type: 'doc', id: 'guide/mini-program', label: '1.3.10 小程序与跨平台' },
            { type: 'doc', id: 'guide/plugin', label: '1.3.11 插件' },
            { type: 'doc', id: 'guide/serialization', label: '1.3.12 序列化' },
            { type: 'doc', id: 'guide/shapes', label: '1.3.13 图元手册' },
            { type: 'doc', id: 'guide/text', label: '1.3.14 文本' },
            { type: 'doc', id: 'guide/theme-and-style', label: '1.3.15 主题与样式机制' },
            { type: 'doc', id: 'guide/viewport', label: '1.3.16 视口与缩放' },
          ],
        },
        {
          type: 'category',
          label: '1.4 架构设计',
          items: [
            { type: 'doc', id: 'architecture/README', label: '1.4.0 架构设计概览' },
            { type: 'doc', id: 'architecture/runtime', label: '1.4.1 运行时链路' },
            { type: 'doc', id: 'architecture/component-model', label: '1.4.2 组件模型' },
            { type: 'doc', id: 'architecture/coordinate-system', label: '1.4.3 坐标系与矩阵组合' },
            { type: 'doc', id: 'architecture/rendering-performance', label: '1.4.4 渲染与性能' },
            { type: 'doc', id: 'architecture/event-system', label: '1.4.5 事件系统' },
            { type: 'doc', id: 'architecture/serialization', label: '1.4.6 序列化' },
            { type: 'doc', id: 'architecture/interaction-animation', label: '1.4.7 交互与动画' },
            { type: 'doc', id: 'architecture/compatibility', label: '1.4.8 多运行时兼容' },
            { type: 'doc', id: 'architecture/roadmap', label: '1.4.9 路线图' },
            { type: 'doc', id: 'architecture/worker-offscreen', label: '1.4.10 Worker / OffscreenCanvas 渲染' },
            { type: 'doc', id: 'architecture/viewport-zoom', label: '1.4.11 视口缩放' },
            { type: 'doc', id: 'architecture/alignment-guide', label: '1.4.12 对齐吸附' },
            { type: 'doc', id: 'architecture/gap-analysis', label: '1.4.13 能力缺口分析' },
            { type: 'doc', id: 'architecture/accessibility', label: '1.4.14 无障碍（a11y）原语' },
            { type: 'doc', id: 'architecture/app-driven-review', label: '1.4.15 应用驱动的引擎评估' },
            { type: 'doc', id: 'architecture/link-port-evaluation', label: '1.4.16 连线端点（插槽）扩展评估' },
            { type: 'doc', id: 'architecture/i18n-boundary', label: '1.4.17 i18n 边界（引擎 / 组件库 / 应用）' },
            { type: 'doc', id: 'architecture/animation-architecture', label: '1.4.18 动画机制（目标架构与约束）' },
            { type: 'doc', id: 'architecture/theme', label: '1.4.19 主题机制' },
            { type: 'doc', id: 'architecture/link', label: '1.4.20 连线机制' },
            { type: 'doc', id: 'architecture/control-panel', label: '1.4.21 控制面板' },
            { type: 'doc', id: 'architecture/plugin', label: '1.4.22 插件机制' },
            { type: 'doc', id: 'architecture/layout', label: '1.4.23 布局机制' },
            { type: 'doc', id: 'architecture/export', label: '1.4.24 导出（SVG）' },
          ],
        },
        {
          type: 'category',
          label: '1.5 API 参考',
          items: [
            { type: 'doc', id: 'api/ice', label: '1.5.1 ICE 类参考' },
            { type: 'doc', id: 'api/ice-component', label: '1.5.2 ICEComponent 参考' },
          ],
        },
        {
          type: 'category',
          label: '1.6 二次开发',
          items: [
            { type: 'doc', id: 'advanced/secondary-development', label: '1.6.1 基于 ice-render 内核二次开发' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '2. 家族产品 · 应用层',
      items: [
        {
          type: 'category',
          label: `2.1 Entity Designer v${V.entityDesigner}`,
          items: [
            { type: 'doc', id: 'entity-designer/index', label: '概览' },
            { type: 'doc', id: 'entity-designer/power-symbol-spec', label: '电力符号记法' },
            { type: 'doc', id: 'entity-designer/power-secondary-spec', label: '厂站二次侧记法' },
            { type: 'doc', id: 'entity-designer/water-process-spec', label: '水处理工艺记法' },
          ],
        },
        {
          type: 'category',
          label: `2.2 ice-chart v${V.iceChart}`,
          items: [
            { type: 'doc', id: 'ice-chart/index', label: '概览' },
            { type: 'doc', id: 'ice-chart/annotation-design', label: '标注能力设计' },
          ],
        },
        {
          type: 'category',
          label: `2.3 ice-web-components v${V.iceWebComponents}`,
          items: [
            { type: 'doc', id: 'ice-web-components/index', label: '2.3.0 概览' },
            { type: 'doc', id: 'ice-web-components/architecture', label: '2.3.1 架构思路' },
            { type: 'doc', id: 'ice-web-components/components', label: '2.3.2 组件速查' },
            {
              type: 'category',
              label: '2.3.3 API 参考',
              items: [
                { type: 'doc', id: 'ice-web-components/api/README', label: 'API 总览' },
                { type: 'doc', id: 'ice-web-components/api/basic', label: '基础组件' },
                { type: 'doc', id: 'ice-web-components/api/data-entry', label: '数据录入' },
                { type: 'doc', id: 'ice-web-components/api/data-entry-popups', label: '数据录入（浮层类）' },
                { type: 'doc', id: 'ice-web-components/api/data-display', label: '数据展示' },
                { type: 'doc', id: 'ice-web-components/api/feedback', label: '反馈与状态' },
                { type: 'doc', id: 'ice-web-components/api/navigation', label: '导航' },
                { type: 'doc', id: 'ice-web-components/api/core', label: '核心与布局' },
                { type: 'doc', id: 'ice-web-components/api/helpers', label: '工具函数' },
                { type: 'doc', id: 'ice-web-components/api/models', label: '模型' },
              ],
            },
            {
              type: 'category',
              label: '2.3.4 指南',
              items: [
                { type: 'doc', id: 'ice-web-components/guides/examples', label: '示例与场景' },
                { type: 'doc', id: 'ice-web-components/guides/custom-components', label: '写一个自己的组件' },
                { type: 'doc', id: 'ice-web-components/guides/theming', label: '主题与配色' },
                { type: 'doc', id: 'ice-web-components/guides/forms', label: '表单与校验' },
                { type: 'doc', id: 'ice-web-components/guides/overlays', label: '浮层指南' },
                { type: 'doc', id: 'ice-web-components/guides/layout', label: '画布内布局' },
                { type: 'doc', id: 'ice-web-components/guides/testing', label: '测试' },
                { type: 'doc', id: 'ice-web-components/guides/migration', label: '迁移说明' },
                { type: 'doc', id: 'ice-web-components/guides/row-painter-migration', label: 'RowPainter 迁移' },
              ],
            },
          ],
        },
        { type: 'doc', id: 'ice-smart-water/index', label: `2.4 ice-smart-water v${V.iceSmartWater}` },
        { type: 'doc', id: 'ice-game/index', label: `2.5 ice-game v${V.iceGame}` },
        {
          type: 'category',
          label: `2.6 ice-agent-console v${V.iceAgentConsole}`,
          items: [
            { type: 'doc', id: 'ice-agent-console/index', label: '概览' },
            { type: 'doc', id: 'ice-agent-console/upstream-gaps', label: '上游差距盘点' },
          ],
        },
        {
          type: 'category',
          label: '2.7 DSL 层',
          items: [
            { type: 'doc', id: 'ice-render-dsl/index', label: `2.7.1 ice-render-dsl v${V.iceRenderDsl}` },
            { type: 'doc', id: 'ice-chart-dsl/index', label: `2.7.2 ice-chart-dsl v${V.iceChartDsl}` },
            { type: 'doc', id: 'ice-entity-designer-dsl/index', label: `2.7.3 ice-entity-designer-dsl v${V.entityDesignerDsl}` },
            { type: 'doc', id: 'ice-web-components-dsl/index', label: `2.7.4 ice-web-components-dsl v${V.iceWebComponentsDsl}` },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '3. 工程约定',
      items: [
        { type: 'doc', id: 'conventions/member-ordering', label: '3.1 成员顺序契约' },
        { type: 'doc', id: 'conventions/app-pages', label: '3.2 应用层页面写法' },
      ],
    },
  ],
};

module.exports = sidebars;
