/**
 * Sidebar 组织原则：引擎优先，产品殿后。
 *
 * 顶层为「显式学习路径」，内层目录仍用 autogenerated（往 guide / architecture
 * 里加文档会自动出现，无需改这里）。这样既有清晰的首页阅读顺序，又不牺牲可维护性。
 *
 * 顺序：
 *   1. 介绍（intro）
 *   2. 快速上手（入门）
 *   3. 指南（怎么做）
 *   4. 架构设计（怎么实现）
 *   5. API 参考
 *   6. 二次开发（进阶）
 *   7. 家族产品 —— 基于 ice-render 构建的上层应用（Entity Designer / ice-chart /
 *      ice-web-components），放在最底部，明确「它们是引擎之上的产品」。
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '快速上手',
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: '指南',
      items: [{ type: 'autogenerated', dirName: 'guide' }],
    },
    {
      type: 'category',
      label: '架构设计',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'API 参考',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: '二次开发',
      items: [{ type: 'autogenerated', dirName: 'advanced' }],
    },
    {
      type: 'category',
      label: '家族产品 · 基于 ice-render 构建',
      items: [
        { type: 'autogenerated', dirName: 'entity-designer' },
        { type: 'autogenerated', dirName: 'ice-chart' },
        { type: 'autogenerated', dirName: 'ice-web-components' },
      ],
    },
  ],
};

module.exports = sidebars;
